#!/usr/bin/env sh

# This script is derived from `install.sh` in Danny van Kooten's "browserpass":
# https://github.com/dannyvankooten/browserpass

set -e

APP_NAME="passff"
VERSION="_VERSIONHOLDER_"
DOWNLOAD_BASE="https://codeberg.org/PassFF/passff-host/releases/download/$VERSION"
HOST_URL="$DOWNLOAD_BASE/passff.py"
MANIFEST_URL="$DOWNLOAD_BASE/passff.json"
KERNEL_NAME=$(uname -s)

# Find target dirs for various browsers & OS'es
# https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-location
# https://wiki.mozilla.org/WebExtensions/Native_Messaging
if [ "$KERNEL_NAME" = 'Darwin' ]; then
  if [ "$(whoami)" = "root" ]; then
    TARGET_DIR_CHROME="/Library/Google/Chrome/NativeMessagingHosts"
    TARGET_DIR_CHROMIUM="/Library/Application Support/Chromium/NativeMessagingHosts"
    TARGET_DIR_FIREFOX="/Library/Application Support/Mozilla/NativeMessagingHosts"
    TARGET_DIR_VIVALDI="/Library/Application Support/Vivaldi/NativeMessagingHosts"
    TARGET_DIR_LIBREWOLF="/Library/Application Support/LibreWolf/NativeMessagingHosts"
  else
    TARGET_DIR_CHROME="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
    TARGET_DIR_CHROMIUM="$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
    TARGET_DIR_FIREFOX="$HOME/Library/Application Support/Mozilla/NativeMessagingHosts"
    TARGET_DIR_VIVALDI="$HOME/Library/Application Support/Vivaldi/NativeMessagingHosts"
    TARGET_DIR_LIBREWOLF="$HOME/Library/Application Support/LibreWolf/NativeMessagingHosts"
  fi
else
  if [ "$(whoami)" = "root" ]; then
    TARGET_DIR_CHROME="/etc/opt/chrome/native-messaging-hosts"
    TARGET_DIR_CHROMIUM="/etc/chromium/native-messaging-hosts"
    TARGET_DIR_FIREFOX="/usr/lib/mozilla/native-messaging-hosts"
    TARGET_DIR_VIVALDI="/etc/vivaldi/native-messaging-hosts"
    TARGET_DIR_LIBREWOLF="/usr/lib/librewolf/native-messaging-hosts"
  else
    TARGET_DIR_CHROME="$HOME/.config/google-chrome/NativeMessagingHosts"
    TARGET_DIR_CHROMIUM="$HOME/.config/chromium/NativeMessagingHosts"
    TARGET_DIR_FIREFOX="$HOME/.mozilla/native-messaging-hosts"
    TARGET_DIR_VIVALDI="$HOME/.config/vivaldi/NativeMessagingHosts"
    TARGET_DIR_LIBREWOLF="$HOME/.librewolf/native-messaging-hosts"
    # Sandboxed (containerised) Firefox packages keep their Native Messaging
    # manifests inside the package's private home, not in ~/.mozilla.
    TARGET_DIR_FIREFOX_SNAP="$HOME/snap/firefox/common/.mozilla/native-messaging-hosts"
    TARGET_DIR_FIREFOX_FLATPAK="$HOME/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts"
  fi
fi

usage() {
  echo "Usage: $0 [OPTION] [chrome|chromium|firefox|firefox-snap|firefox-flatpak|opera|vivaldi|librewolf]

  Examples:
    $0 firefox          # Install host app for a regular Mozilla Firefox
    $0 firefox-snap     # Install host app for Snap Firefox (Ubuntu)
    $0 firefox-flatpak  # Install host app for Flatpak Firefox

  Options:
    -l, --local    Install files from disk instead of downloading them
    -h, --help     Show this message"
}

# generate_wrapper SANDBOX WRAPPER_PATH PYTHON3_PATH HOST_PATH
#
# Writes a small shell wrapper that the (sandboxed) browser launches instead of
# the Python host. Its only job is to reach the real host environment and then
# `exec` the Python host so that the wrapper process is *replaced*: stdin,
# stdout and stderr file descriptors are inherited untouched. This is essential
# because Native Messaging is a binary protocol over stdin/stdout (a 4-byte
# little-endian length prefix followed by a JSON payload). The wrapper therefore
# MUST NOT write anything to stdout itself — any stray byte corrupts the stream.
generate_wrapper() {
  _sandbox="$1"
  _wrapper="$2"
  _python="$3"
  _host="$4"

  case "$_sandbox" in
    flatpak)
      # Inside the Flatpak sandbox we jump to the host with flatpak-spawn.
      # flatpak-spawn forwards stdin/stdout/stderr to the host process, so the
      # Native Messaging stream stays intact. The host paths ($_python, $_host)
      # are valid on the host because ~/.var/app/<id>/ is bind-mounted at the
      # same absolute path both inside and outside the sandbox.
      cat > "$_wrapper" <<EOF
#!/bin/sh
# PassFF Native Messaging wrapper for Flatpak Firefox (generated by install_host_app.sh).
# Bridges from the Flatpak sandbox to the host so that pass/gpg and
# ~/.password-store are reachable. Do not log to stdout: it carries the IPC stream.
exec flatpak-spawn --host "$_python" "$_host" "\$@"
EOF
      ;;

    snap)
      # A Snap-confined Firefox cannot exec the host's pass/gpg at all (the snap
      # runtime shadows /usr and AppArmor blocks running host binaries via
      # hostfs). It *can* connect to a Unix socket in its own writable area, so
      # this wrapper just runs the forwarder (with the snap runtime's python3),
      # which bridges the Native Messaging stream to the host daemon. $5 is the
      # forwarder path, $6 the socket path.
      _forward="$5"
      _socket="$6"
      cat > "$_wrapper" <<EOF
#!/bin/sh
# PassFF Native Messaging wrapper for Snap Firefox (generated by install_host_app.sh).
# Bridges stdin/stdout to the host daemon over a Unix socket. Do not log to
# stdout: it carries the Native Messaging IPC stream. python3 here is the snap
# runtime's interpreter (the host one is not reachable from inside the snap).
exec python3 "$_forward" "$_socket"
EOF
      ;;
  esac
}

# copy_source BASENAME DEST SEDPROG
#
# Installs one source file (from local disk with --local, or downloaded
# otherwise) into DEST, piping it through `sed -e SEDPROG` (pass "" for none).
copy_source() {
  _bn="$1"
  _dest="$2"
  _sed="$3"
  if [ "$USE_LOCAL_FILES" = true ]; then
    sed -e "$_sed" "$(dirname "$0")/$_bn" > "$_dest"
  else
    curl -sSL "$DOWNLOAD_BASE/$_bn" | sed -e "$_sed" > "$_dest"
  fi
}

# install_snap_daemon_service DAEMON_PATH SOCKET_PATH
#
# Writes and (best-effort) starts a systemd --user service that keeps the host
# bridge daemon running outside the snap confinement.
install_snap_daemon_service() {
  _daemon="$1"
  _socket="$2"
  _unit_dir="$HOME/.config/systemd/user"
  _unit="$_unit_dir/passff-host.service"

  mkdir -p "$_unit_dir"
  cat > "$_unit" <<EOF
[Unit]
Description=PassFF Native Messaging host bridge for Snap Firefox

[Service]
Type=simple
ExecStart=$PYTHON3_PATH $_daemon $_socket
Restart=on-failure

[Install]
WantedBy=default.target
EOF

  if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload 2>/dev/null || true
    # Expose the graphical session env so gpg's pinentry can pop up if needed.
    systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XAUTHORITY 2>/dev/null || true
    if systemctl --user enable --now passff-host.service 2>/dev/null; then
      echo "Started passff-host.service (the host-side bridge daemon)."
    else
      echo "WARNING: could not start passff-host.service automatically. Run:"
      echo "           systemctl --user enable --now passff-host.service"
    fi
  else
    echo "NOTE: systemd --user not available. Start the daemon manually:"
    echo "        $PYTHON3_PATH $_daemon $_socket &"
  fi
}

# install_snap_bridge TARGET_DIR HOST_PY_PATH WRAPPER_PATH
#
# Sets up the full Snap bridge: a forwarder (runs inside the snap), a host
# daemon (runs outside, talks to pass/gpg), the wrapper the browser launches,
# and the systemd user service that keeps the daemon alive.
install_snap_bridge() {
  _td="$1"
  _hostpy="$2"
  _wrapper="$3"
  _forward="$_td/$APP_NAME-snap-forward.py"
  _daemon="$_td/$APP_NAME-host-daemon.py"
  # The socket lives in the snap's own writable area, which is reachable both
  # from the host (directly) and from inside the snap (as $HOME/...).
  _socket="$HOME/snap/firefox/common/$APP_NAME-host.sock"

  # Forwarder runs inside the snap with the snap runtime's python3, so leave
  # its shebang/interpreter alone (the host python is not reachable there).
  copy_source "$APP_NAME-snap-forward.py" "$_forward" ""
  chmod a+x "$_forward"

  # Daemon runs on the host: patch its shebang to the host python3 (HOST_SED).
  copy_source "$APP_NAME-host-daemon.py" "$_daemon" "$HOST_SED"
  chmod a+x "$_daemon"

  generate_wrapper snap "$_wrapper" "$PYTHON3_PATH" "$_hostpy" "$_forward" "$_socket"
  chmod a+x "$_wrapper"

  install_snap_daemon_service "$_daemon" "$_socket"
  configure_snap_portal_pref
}

# configure_snap_portal_pref
#
# Snap Firefox resolves Native Messaging hosts through the XDG Desktop Portal
# (org.freedesktop.portal.WebExtensions). On many systems that portal cannot
# locate the host and replies "NotFound", so the host is never launched. We
# disable the portal for Native Messaging (pref value 0 = never) via user.js in
# every Firefox profile, which makes Firefox fall back to launching the manifest
# directly -> our wrapper -> the socket bridge.
configure_snap_portal_pref() {
  _ff_base="$HOME/snap/firefox/common/.mozilla/firefox"
  [ -d "$_ff_base" ] || return 0
  _pref='user_pref("widget.use-xdg-desktop-portal.native-messaging", 0);'
  _done=0
  for _prof in "$_ff_base"/*/; do
    # Only touch real profile directories (those Firefox has initialised).
    [ -f "$_prof/prefs.js" ] || [ -f "$_prof/times.json" ] || continue
    _uj="$_prof/user.js"
    # Drop any previous setting of this pref, then add ours. Use an
    # unconditional mv: if the filtered output is empty (the file held only
    # this pref) grep exits non-zero, so we must not gate mv on its status.
    if [ -f "$_uj" ]; then
      grep -v 'widget.use-xdg-desktop-portal.native-messaging' "$_uj" > "$_uj.tmp" 2>/dev/null || true
      mv "$_uj.tmp" "$_uj"
    fi
    echo "$_pref" >> "$_uj"
    _done=1
  done
  if [ "$_done" = 1 ]; then
    echo "Disabled the (broken) Native Messaging portal in your Firefox profiles."
    echo "Restart Firefox once for this to take effect."
  fi
}

# install_host TARGET_DIR SANDBOX BROWSER_NAME
#
# Installs the Python host + manifest (+ wrapper for sandboxed browsers) into a
# single target directory. Relies on the globals PYTHON3_PATH, PASS_PATH,
# HOST_SED and USE_LOCAL_FILES being set up beforehand.
install_host() {
  _target_dir="$1"
  _sandbox="$2"
  _browser_name="$3"

  _host_file="$_target_dir/$APP_NAME.py"
  _manifest_file="$_target_dir/$APP_NAME.json"
  _wrapper_file="$_target_dir/$APP_NAME-wrapper.sh"

  # For sandboxed browsers the browser process cannot exec the Python host
  # directly with a working environment, so the manifest points at a wrapper
  # that bridges to the host system.
  if [ -n "$_sandbox" ]; then
    _manifest_target="$_wrapper_file"
  else
    _manifest_target="$_host_file"
  fi

  echo "Installing $_browser_name host config"

  # Create config dir if not existing
  mkdir -p "$_target_dir"

  _manifest_target_esc="$(echo "$_manifest_target" | sed -e 's/@/\\@/g')"
  # Replace path to host (wrapper for sandboxed browsers, Python host otherwise)
  _manifest_sed="s@PLACEHOLDER@$_manifest_target_esc@;"

  if [ "$USE_LOCAL_FILES" = true ]; then
    sed -e "${HOST_SED}"      "$(dirname "$0")/passff.py"   >  "$_host_file"
    sed -e "${_manifest_sed}" "$(dirname "$0")/passff.json" >  "$_manifest_file"
  else
    # Download native host script and manifest
    curl -sSL "$HOST_URL"     | sed -e "${HOST_SED}"      > "$_host_file"
    curl -sSL "$MANIFEST_URL" | sed -e "${_manifest_sed}" > "$_manifest_file"
  fi

  # Set permissions for the manifest so that all users can read it.
  chmod a+x "$_host_file"
  chmod o+r "$_manifest_file"

  # Set up the sandbox bridge, if needed.
  if [ "$_sandbox" = "flatpak" ]; then
    # Flatpak: a thin wrapper that jumps to the host with flatpak-spawn.
    generate_wrapper flatpak "$_wrapper_file" "$PYTHON3_PATH" "$_host_file"
    chmod a+x "$_wrapper_file"
    # By default the Flatpak Firefox is NOT allowed to talk to the Flatpak
    # session helper, so flatpak-spawn --host would fail. Grant just that.
    if command -v flatpak >/dev/null 2>&1 && \
       flatpak override --user --talk-name=org.freedesktop.Flatpak org.mozilla.firefox 2>/dev/null; then
      echo "Granted org.mozilla.firefox permission to use flatpak-spawn --host."
    else
      echo "WARNING: could not grant the flatpak-spawn permission automatically."
      echo "         Please run this once yourself:"
      echo "           flatpak override --user --talk-name=org.freedesktop.Flatpak org.mozilla.firefox"
    fi
  elif [ "$_sandbox" = "snap" ]; then
    # Snap: a socket bridge to a host-side daemon (the snap cannot run pass/gpg).
    install_snap_bridge "$_target_dir" "$_host_file" "$_wrapper_file"
  fi

  echo "Native messaging host for $_browser_name has been installed to $_target_dir."
}

# detect_firefox_variants
#
# Echoes a space-separated list of installed Firefox flavours among:
# "regular", "snap", "flatpak". Used when the user asks for plain "firefox".
detect_firefox_variants() {
  _found=""

  if [ "$KERNEL_NAME" != 'Darwin' ]; then
    # Snap
    if [ -d "$HOME/snap/firefox" ] || \
       { command -v snap >/dev/null 2>&1 && snap list firefox >/dev/null 2>&1; }; then
      _found="$_found snap"
    fi
    # Flatpak
    if [ -d "$HOME/.var/app/org.mozilla.firefox" ] || \
       { command -v flatpak >/dev/null 2>&1 && flatpak info org.mozilla.firefox >/dev/null 2>&1; }; then
      _found="$_found flatpak"
    fi
  fi

  # Regular (non-containerised) Firefox: a firefox binary that is not the
  # snap shim, or an existing ~/.mozilla profile directory.
  _ff_bin="$(command -v firefox 2>/dev/null || true)"
  if [ -n "$_ff_bin" ]; then
    _ff_real="$(readlink -f "$_ff_bin" 2>/dev/null || echo "$_ff_bin")"
    case "$_ff_real" in
      /snap/*) : ;;  # snap shim, already covered above
      *) _found="$_found regular" ;;
    esac
  elif [ -d "$HOME/.mozilla" ]; then
    _found="$_found regular"
  fi

  echo "$_found"
}

while [ $# -gt 0 ]; do
  case $1 in
    chrome)
      BROWSER_NAME="Chrome"
      TARGET_DIR="$TARGET_DIR_CHROME"
      ;;
    chromium)
      BROWSER_NAME="Chromium"
      TARGET_DIR="$TARGET_DIR_CHROMIUM"
      ;;
    firefox)
      # Auto-detect which Firefox flavour(s) are installed and install into
      # each one (regular, Snap and/or Flatpak).
      FIREFOX_AUTO=true
      ;;
    firefox-snap)
      BROWSER_NAME="Firefox (Snap)"
      TARGET_DIR="$TARGET_DIR_FIREFOX_SNAP"
      SANDBOX="snap"
      ;;
    firefox-flatpak)
      BROWSER_NAME="Firefox (Flatpak)"
      TARGET_DIR="$TARGET_DIR_FIREFOX_FLATPAK"
      SANDBOX="flatpak"
      ;;
    librewolf)
      BROWSER_NAME="Librewolf"
      TARGET_DIR="$TARGET_DIR_LIBREWOLF"
      ;;
    opera)
      BROWSER_NAME="Opera"
      TARGET_DIR="$TARGET_DIR_VIVALDI"
      ;;
    vivaldi)
      BROWSER_NAME="Vivaldi"
      TARGET_DIR="$TARGET_DIR_VIVALDI"
      ;;
    -l|--local)
      USE_LOCAL_FILES=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
  shift
done

PYTHON3_PATH="$(which python3)"
if [ -x "$PYTHON3_PATH" ]; then
  echo "Python 3 executable located at $PYTHON3_PATH"
else
  echo "Python 3 executable not found, but Python 3 is required for PassFF to work!"
  exit 1
fi

PASS_PATH="$(which pass || which gopass)"
if [ -x "$PASS_PATH" ]; then
  echo "Pass executable located at $PASS_PATH"
else
  echo "Pass executable not found, but Pass is required for PassFF to work!"
  exit 1
fi

if [ -z "$TARGET_DIR" ] && [ "$FIREFOX_AUTO" != true ]; then
  usage
  exit 1
fi

# Pre-compute the parts of the sed program that are shared across every target.
PATH_ESC="$(echo "$PATH" | sed -e 's/@/\\@/g')"
PASS_PATH_ESC="$(echo "$PASS_PATH" | sed -e 's/@/\\@/g')"
PYTHON3_PATH_ESC="$(echo "$PYTHON3_PATH" | sed -e 's/@/\\@/g')"

# Replace path to python3 executable \
# Replace path to pass (only in a line starting with "COMMAND =") \
# Set the PATH to match this script's \
HOST_SED=" \
1 s@.*@#!${PYTHON3_PATH_ESC}@; \
/^COMMAND *=/s@\"pass\"@\"$PASS_PATH_ESC\"@; \
s@\"PATH\":.*@\"PATH\": \"$PATH_ESC\"@; \
"

if [ "$FIREFOX_AUTO" = true ]; then
  VARIANTS="$(detect_firefox_variants)"
  if [ -z "$VARIANTS" ]; then
    echo "No Firefox installation detected; installing for a regular Firefox anyway."
    VARIANTS="regular"
  else
    echo "Detected Firefox flavour(s):$VARIANTS"
  fi
  for variant in $VARIANTS; do
    case "$variant" in
      regular) install_host "$TARGET_DIR_FIREFOX"         ""        "Firefox" ;;
      snap)    install_host "$TARGET_DIR_FIREFOX_SNAP"    "snap"    "Firefox (Snap)" ;;
      flatpak) install_host "$TARGET_DIR_FIREFOX_FLATPAK" "flatpak" "Firefox (Flatpak)" ;;
    esac
  done
else
  install_host "$TARGET_DIR" "$SANDBOX" "$BROWSER_NAME"
fi
